import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/page";
import Footer from "@/components/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <title>Home-Page 1 || Charity</title>

        <link rel="shortcut icon" type="image/x-icon" href="./asstes/img/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css?family=Lato:400,700"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
          rel="stylesheet"
          type="text/css"
        />

        <link rel="stylesheet" href="./assets/master.css" />
      </head>

      <body className={inter.className}
      >
        <Header />
        {children}
        <Footer />
        <script src="./assets/js/vendor/modernizr-2.8.3.min.js"></script>
        <script src="./assets/js/vendor/jquery-1.12.0.min.js"></script>
        <script src="./assets/js/bootstrap.min.js"></script>
        <script src="./assets/js/owl.carousel.min.js"></script>
        <script src="./assets/js/jquery-ui.min.js"></script>
        <script src="./assets/js/wow.min.js"></script>
        <script src="./assets/js/venobox.min.js"></script>
        <script src="./assets/js/jquery.mixitup.js"></script>
        <script src="./assets/js/jquery.elevateZoom-3.0.8.min.js"></script>
        <script
          src="./assets/lib/js/jquery.nivo.slider.js"
          type="text/javascript"
        ></script>
        <script src="./assets/lib/home.js" type="text/javascript"></script>
        <script src="./assets/js/jquery.meanmenu.js"></script>
        <script src="./assets/js/plugins.js"></script>
        <script src="./assets/js/main.js"></script>
      </body>
    </html>
  );
}
